import Head from 'next/head';

interface HomeProps {
    poolsCount: number;
}

export default function Home(props: HomeProps) {
    return (
        <div>
            <Head>
                <meta charSet="utf-8" />
                <link rel="icon" href="https://raw.githubusercontent.com/Luk4x/user-register-interface/main/public/favicon.ico" />
                <meta name="description" content="Generated by create next app" />
                <title>Create Next App</title>
            </Head>
            <h1>Contagem: {props.poolsCount}</h1>
        </div>
    );
}

export const getServerSideProps = async () => {
    const poolsCount = await fetch('http://localhost:3333/pools/count').then(data => data.json());
    console.log(poolsCount);

    return {
        props: { ...poolsCount }
    };
};
